# Penggunaan COUNT(DISTINCT), STRING_AGG
SELECT 
    COUNTRY,
    COUNT(DISTINCT CITY) AS TOTAL_CITY,
    STRING_AGG (DISTINCT CITY, "-") AS LIST_CITY

FROM 
`my-project-1-data-analyst.satu.sale`
GROUP BY COUNTRY
ORDER BY TOTAL_CITY DESC
