SELECT 
  DISTINCT COUNTRY,
  CITY,
  STATUS,
  EXTRACT(DAY FROM ORDERDATE) AS DAY,
  EXTRACT(WEEK FROM ORDERDATE) AS WEEK,
  EXTRACT(MONTH FROM ORDERDATE) AS MONTH,
  EXTRACT(QUARTER FROM ORDERDATE) AS QUARTER,
  EXTRACT(YEAR FROM ORDERDATE) AS YEAR,
  FORMAT_DATE("%A", ORDERDATE) AS DAY_FULLNAME,
  FORMAT_DATE("%a", ORDERDATE) AS DAY_SHORTNAME,
  FORMAT_DATE("%B", ORDERDATE) AS MONTH_FULLNAME,
  FORMAT_DATE("%b", ORDERDATE) AS MONTH_SHORTNAME,
  DATE_TRUNC(ORDERDATE, MONTH) AS START_OF_MONTH,
  EXTRACT (DAYOFWEEK FROM ORDERDATE) AS DAY_OF_WEEK,
  CAST(FORMAT_DATE("%j", ORDERDATE)AS INT64 ) AS DAY_OF_YEAR
FROM 
  `my-project-1-data-analyst.satu.sale`
